Squashed commit of the following:
commit 79182dd3888164365d03d1b11983ea4194267849
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:38:25 2022 -0700

    Update pvc.py

commit 420bbfd9bde30279532d33f0c2957f8a6da61e75
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:29:55 2022 -0700

    Update pvc.py

commit 303c05526091083df3af339751812cf442ceaebb
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:27:03 2022 -0700

    PVC InvalidStateError: invalid state hopefully fixed

commit 316a276e131ba06509ba33887907658dfde1b472
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:21:47 2022 -0700

    Update pvc.py

commit 542897bd3e30722710c9901a19ad93aa771df988
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:20:54 2022 -0700

    Update pvc.py

commit 6ac3c1f77dc602f4d86fa513114d75272595b75a
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:17:09 2022 -0700

    Update pvc.py

commit 2fc4cc855c26a936143bcbe5da63ed9f12c49c0a
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:11:01 2022 -0700

    Update pvc.py

commit 88a4ec70a245c0279a9477d4e0f51357f27324ed
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:09:38 2022 -0700

    Update pvc.py

commit 8db8295ffecd3724cd3141791b6d9a0314239d0e
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:04:28 2022 -0700

    Reverted Changes to pvc.checks()

commit 9df23037aad8595e1dc694dafc54f813ec2288ab
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:01:22 2022 -0700

    Update pvc.py

commit 3c4d668440a305d9d29cb402932ec4e0519ea40e
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 13:00:00 2022 -0700

    Update pvc.py

commit 9cd8697b7124b02b911b732d50cffbe557237b5f
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:58:49 2022 -0700

    Update pvc.py

commit 36adb22e9d15c6ec8b9835afaa9e9bb2f36e0044
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:58:04 2022 -0700

    Update pvc.py

commit 4ebfeaf2731ff62376991110bb0538eb9d627502
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:50:39 2022 -0700

    Update pvc.py

commit 932be21011537c9daa4c2b463b0a60a4512cc5a0
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:46:55 2022 -0700

    Update pvc.py

commit 6a40808661d190c0420afdf22d85ba331b251b02
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:46:20 2022 -0700

    Update pvc.py

commit 289a02b28f2bcd5988b252a6572215ccd60ec7ea
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:33:35 2022 -0700

    Update pvc.py

commit e6fbfb1a34901da900d2d6af0ccaf979640c38ba
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:31:52 2022 -0700

    Update pvc.py

commit cdda2be32c0780cd6f0edea3cd966231dc4d0d40
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:28:28 2022 -0700

    Fixed message for transfer

    Fixed message for trying to transfer a vc that doesn't belong to you

commit 64b2b8b981cbb66a65d54ef35812e8232e526d51
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:24:35 2022 -0700

    Fixed message

commit bf8eb43e67b6849df7cfa61aa00011f3471ba970
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:20:49 2022 -0700

    Fixed checks for transfer

    You can no longer you vc to someone who owns another channel

commit fa26cea90c0b1221da24fe50cf195bdbec7ebf09
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:13:38 2022 -0700

    Update pvc.py

commit c41b13049fc21e5b9b9c9836e3c7bee6800a10a5
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:11:35 2022 -0700

    Dang don't know how I missed that one

commit 4ea4c2421a23b9c30b345e276c3e754a5205d9c3
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 12:06:17 2022 -0700

    More optimizations

commit b1aa58320887d2ab6d80512e488ad23aa7fd3ba6
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:51:38 2022 -0700

    Update README.md

commit 2122c70d7197c6541e8fd44697ef13bd0b2076c1
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:44:38 2022 -0700

    Update pvc.py

commit 693b7898872a67ffec354ec09dc1726e4762c16e
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:39:16 2022 -0700

    Fixed vc create clearing itself

commit 24c182559304a8a7bebca21f70ce229f1f23050d
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:35:35 2022 -0700

    Fixed timed ping spamming console

    Every time someone sent the bot a message in dms it would spam AttributeError: 'NoneType' object has no attribute 'id'

commit 82ea84b0ed6e93fb8be9bab7dfebe090a30ffaef
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:14:52 2022 -0700

    Update pvc.py

commit 77ce43cb03fc2d4c499cc98f128e678a54c11c4f
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:13:24 2022 -0700

    Update pvc.py

commit 2748cac872cd525d633f129773404eca2ee7b466
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:06:34 2022 -0700

    Update pvc.py

commit 456b0c2f62a9eaa55472654dcb475f85826b98d1
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:05:28 2022 -0700

    Update pvc.py

commit e7144547894f2fcd9493e4131d01a44469548a69
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:53:19 2022 -0700

    Simplified vc region even more :)

commit 2ebc394c263b546a98924208476700eeb2539928
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:31:08 2022 -0700

    Fixed vc region setting to auto

commit 353ac382d104bb9454d081b6c0c5d21f2a9a7ab7
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:29:03 2022 -0700

    Update codeql-analysis.yml

commit f896fc995f9f47d541900948ea3154fd864a3571
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:11:11 2022 -0700

    Code optimizations