Squashed commit of the following:
commit 2122c70d7197c6541e8fd44697ef13bd0b2076c1
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:44:38 2022 -0700

    Update pvc.py

commit 693b7898872a67ffec354ec09dc1726e4762c16e
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:39:16 2022 -0700

    Fixed vc create clearing itself

commit 24c182559304a8a7bebca21f70ce229f1f23050d
Author: Joseph <jnjbros2@gmail.com>
Date:   Fri Aug 19 11:35:35 2022 -0700

    Fixed timed ping spamming console

    Every time someone sent the bot a message in dms it would spam AttributeError: 'NoneType' object has no attribute 'id'

commit 82ea84b0ed6e93fb8be9bab7dfebe090a30ffaef
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:14:52 2022 -0700

    Update pvc.py

commit 77ce43cb03fc2d4c499cc98f128e678a54c11c4f
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:13:24 2022 -0700

    Update pvc.py

commit 2748cac872cd525d633f129773404eca2ee7b466
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:06:34 2022 -0700

    Update pvc.py

commit 456b0c2f62a9eaa55472654dcb475f85826b98d1
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 20:05:28 2022 -0700

    Update pvc.py

commit e7144547894f2fcd9493e4131d01a44469548a69
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:53:19 2022 -0700

    Simplified vc region even more :)

commit 2ebc394c263b546a98924208476700eeb2539928
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:31:08 2022 -0700

    Fixed vc region setting to auto

commit 353ac382d104bb9454d081b6c0c5d21f2a9a7ab7
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:29:03 2022 -0700

    Update codeql-analysis.yml

commit f896fc995f9f47d541900948ea3154fd864a3571
Author: Joseph <jnjbros2@gmail.com>
Date:   Thu Aug 18 19:11:11 2022 -0700

    Code optimizations